### ISSUE TITLE
using lcars with bootstrap

### ISSUE THREAD

**Issue by geib** [Garrett-/lcars#1]
I am building a new UI to an application and I came across your lcars CSS. My question is can I use lcars with bootstrap CSS, or is lcars complete replacement.?

**Comment by Garrett-** [comment]
I'm sorry to report but I haven't worked on this project in years. However there has been some build up in interest over the last few months. I might consider getting back into it.

To answer your question, as it currently sits right now you could use it along side bootstrap but it would take a lot of tinkering. I would suggest avoiding this project until I can find the time to bring it back up to speed.

If you're interested in taking over please let me know.
